[master]
master01 ansible_host=Master_IP_Address

[workers]
node01 ansible_host=Node01_IP_Address
node02 ansible_host=Node02_IP_Address
#you can add more worker nodes as needed


[kube_cluster:vars]
ansible_user=root
#ansible_ssh_private_key_file=~/.ssh/id_rsa
#Uncomment the above line and provide the path to your SSH private key if you are using key-based authentication instead of password authentication.

[kube_cluster:children]
master
workers
